cache:
  directories:
    - "node_modules"

language: node_js
node_js:
  - "8.10.0"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Has been set in travis-ci.org dashboard; secure
  keep-history: true
  on:
    branch: master
