export const SET_DISEASE_RESULT_LOCAL_ANALYSIS = 'SET_DISEASE_RESULT_LOCAL_ANALYSIS';
export const RESET_DISEASE_RESULT_LOCAL_ANALYSIS = 'RESET_DISEASE_RESULT_LOCAL_ANALYSIS';

export const SET_DISEASE_RESULT_SERVER_ANALYSIS = 'SET_DISEASE_RESULT_SERVER_ANALYSIS';
export const RESET_DISEASE_RESULT_SERVER_ANALYSIS = 'RESET_DISEASE_RESULT_SERVER_ANALYSIS';

export const RESET_DISEASE_RESULT_FULLY = 'RESET_DISEASE_RESULT_FULLY';

export const SET_ECG_RESULT_VISIBILITY = 'SET_ECG_RESULT_VISIBILITY';
export const SET_ECG_EXAMPLES_VISIBILITY = 'SET_ECG_EXAMPLES_VISIBILITY';

export const SET_CURRENT_IMAGE = 'SET_CURRENT_IMAGE';
export const SET_CURRENT_FILE_SHOULD_BE_CLEARED = 'SET_CURRENT_FILE_SHOULD_BE_CLEARED';

export const SET_LANGUAGE = 'SET_LANGUAGE';
