export const SET_DISEASE_RESULT_LOCAL_ANALYSIS = 'SET_DISEASE_RESULT_LOCAL_ANALYSIS';
export const RESET_DISEASE_RESULT_LOCAL_ANALYSIS = 'RESET_DISEASE_RESULT_LOCAL_ANALYSIS';

export const SET_DISEASE_RESULT_SERVER_ANALYSIS = 'SET_DISEASE_RESULT_SERVER_ANALYSIS';
export const RESET_DISEASE_RESULT_SERVER_ANALYSIS = 'RESET_DISEASE_RESULT_SERVER_ANALYSIS';

export const RESET_DISEASE_RESULT_FULLY = 'RESET_DISEASE_RESULT_FULLY';

export const SET_ECG_RESULT_VISIBILITY = 'SET_ECG_RESULT_VISIBILITY';
export const SET_ECG_EXAMPLES_VISIBILITY = 'SET_ECG_EXAMPLES_VISIBILITY';

export const SET_LOCALIZATION = 'SET_LOCALIZATION';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_LOGIN_FETCHING = 'USER_LOGIN_FETCHING';
export const USER_SIGNED_UP = 'USER_SIGNED_UP';
